version: '{build}'
init:
  - 'git config --global core.autocrlf true'
branches:
  only:
    - master
    - develop
skip_commits:
  files:
    - LICENSE
environment:
  nodejs_version: 8
platform:
  - x64
install:
  - ps: 'Install-Product node $env:nodejs_version $env:platform'
  - 'node --version && npm --version'
  - 'npm i -g gitbook-cli'
  - 'choco install calibre'
  - 'refreshenv'
  - 'npm i -g svgexport'
  - 'if exist _book rd /Q /S _book'
  - 'gitbook install'
  - 'gitbook pdf'
  - 'gitbook mobi'
  - 'gitbook epub'
build: off
test: off
artifacts:
  - path: '*.pdf'
  - path: '*.mobi'
  - path: '*.epub'
notifications:
  -
    provider: Slack
    incoming_webhook:
      secure: KzO8e88B0LKqAI0BQM6lNhCIn9rxAava3AcdVJDyTw420OLIAlK+qzzbLXaR0jSH9zIJz9zu0iGS1iaqu9Co+6owYUrHJlBGrUZ/lZNCsDo=
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
